"""empty message

Revision ID: 1c75db3a6280
Revises: 2b69c77c17fb
Create Date: 2018-01-05 13:46:35.846000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c75db3a6280'
down_revision = '2b69c77c17fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    op.drop_column('picture', 'thumb_pic')
    op.drop_column('picture', 'big_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('big_pic', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('picture', sa.Column('thumb_pic', mysql.VARCHAR(length=30), nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
