"""empty message

Revision ID: 470de823c916
Revises: 4d156fbc5aed
Create Date: 2017-12-30 08:59:00.379000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470de823c916'
down_revision = '4d156fbc5aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
