"""empty message

Revision ID: 4d156fbc5aed
Revises: 4e48f9ba228b
Create Date: 2017-12-29 17:52:48.751000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d156fbc5aed'
down_revision = '4e48f9ba228b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
