"""empty message

Revision ID: 4e48f9ba228b
Revises: 21eaff640120
Create Date: 2017-12-29 17:49:47.931000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e48f9ba228b'
down_revision = '21eaff640120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
