"""empty message

Revision ID: 8092403226f2
Revises: 940c9ac13078
Create Date: 2018-01-02 09:02:10.628000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8092403226f2'
down_revision = '940c9ac13078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    op.drop_column('article', 'volume')
    op.drop_column('article', 'date')
    op.drop_column('classfiy', 'height_light')
    op.drop_column('classfiy', 'p_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classfiy', sa.Column('p_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('classfiy', sa.Column('height_light', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('date', mysql.DATETIME(), nullable=False))
    op.add_column('article', sa.Column('volume', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
