"""empty message

Revision ID: 940c9ac13078
Revises: e515bd79f709
Create Date: 2017-12-30 10:17:53.028000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '940c9ac13078'
down_revision = 'e515bd79f709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('article', 'volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.alter_column('article', 'volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('article', 'date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
