"""empty message

Revision ID: 99ec08c394c7
Revises: 8092403226f2
Create Date: 2018-01-02 09:06:31.890000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ec08c394c7'
down_revision = '8092403226f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('volume', sa.Integer(), server_default='0', nullable=False))
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    op.add_column('classfiy', sa.Column('height_light', sa.Integer(), server_default='0', nullable=True))
    op.add_column('classfiy', sa.Column('p_id', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classfiy', 'p_id')
    op.drop_column('classfiy', 'height_light')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'volume')
    # ### end Alembic commands ###
