"""empty message

Revision ID: bd0a7bff896d
Revises: 1c75db3a6280
Create Date: 2018-01-05 13:47:12.340000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0a7bff896d'
down_revision = '1c75db3a6280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    op.add_column('picture', sa.Column('big_pic', sa.String(length=100), nullable=True))
    op.add_column('picture', sa.Column('thumb_pic', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'thumb_pic')
    op.drop_column('picture', 'big_pic')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
