"""empty message

Revision ID: bed8bbf2bf44
Revises: d6604c83bcf3
Create Date: 2018-01-05 12:00:26.233000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed8bbf2bf44'
down_revision = 'd6604c83bcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
