"""empty message

Revision ID: c74c20fb87ba
Revises: 99ec08c394c7
Create Date: 2018-01-02 09:14:29.639000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74c20fb87ba'
down_revision = '99ec08c394c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('date', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=True))
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'date')
    # ### end Alembic commands ###
