"""empty message

Revision ID: d6604c83bcf3
Revises: c74c20fb87ba
Create Date: 2018-01-05 11:01:29.926000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6604c83bcf3'
down_revision = 'c74c20fb87ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('big_pic', sa.String(length=30), nullable=True),
    sa.Column('thumb_pic', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    op.create_index(op.f('ix_classfiy_key_str'), 'classfiy', ['key_str'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classfiy_key_str'), table_name='classfiy')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_table('picture')
    # ### end Alembic commands ###
