"""empty message

Revision ID: e515bd79f709
Revises: d2edd544d5d9
Create Date: 2017-12-30 09:50:43.967000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e515bd79f709'
down_revision = 'd2edd544d5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
