"""empty message

Revision ID: ea99995266f5
Revises: 38f59d7b4526
Create Date: 2017-12-28 16:14:06.143000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea99995266f5'
down_revision = '38f59d7b4526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('article', 'volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'article', 'classfiy', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.alter_column('article', 'volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('article', 'date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
